"use client";
import { ReactNode, useEffect, useState } from "react";

export function AdminNav({email}:{email:string}){async function logout(){await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}return <><div className="subnav"><a href="/admin" style={{display:"flex",alignItems:"center",gap:10,textDecoration:"none"}}><img src="/assets/logo.png" width="42" height="42" style={{borderRadius:"50%"}}/><span>Ease · Admin</span></a><div className="stack"><span className="muted small">{email}</span><button className="secondary" onClick={logout}>Sign out</button></div></div><nav className="admin-nav"><a className="button secondary" href="/admin">Dashboard</a><a className="button secondary" href="/admin/orders">Orders</a><a className="button secondary" href="/admin/products">Products</a><a className="button secondary" href="/admin/customers">Customers</a><a className="button secondary" href="/admin/settings">Settings</a></nav></>}

export function AdminFrame({email,children}:{email:string;children:ReactNode}){return <main className="system-page"><AdminNav email={email}/>{children}</main>}

export function Message({text,kind="error"}:{text:string;kind?:"error"|"success"}){return text?<div className={kind} role="status" style={{margin:"12px 0"}}>{text}</div>:null}

export function AdminLogin({setup=false}:{setup?:boolean}){const [message,setMessage]=useState(""),[busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget);const body=setup?{email:f.get("email"),password:f.get("password"),setupToken:f.get("setupToken")}:{email:f.get("email"),password:f.get("password")};try{const r=await fetch(setup?"/api/admin/setup":"/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to sign in.");location.href="/admin"}catch(e){setMessage(e instanceof Error?e.message:"Network error.")}finally{setBusy(false)}}return <main className="system-page"><div className="subnav"><a href="/">← Ease storefront</a><img src="/assets/logo.png" width="55" height="55" style={{borderRadius:"50%"}}/></div><div style={{maxWidth:520,margin:"8vh auto"}}><div className="eyebrow">Private store access</div><h1>{setup?"Create the first admin":"Admin sign in"}</h1><p>{setup?"Use the one-time setup token from your server environment to create the first administrator.":"Sign in to manage orders, stock, and delivery settings."}</p><form className="panel" onSubmit={submit}>{setup&&<div className="field"><label>One-time setup token</label><input type="password" name="setupToken" autoComplete="off" required /></div>}<div className="field"><label>Email</label><input type="email" name="email" autoComplete="username" required /></div><div className="field"><label>Password {setup&&<span className="muted">(at least 12 characters)</span>}</label><input type="password" name="password" autoComplete={setup?"new-password":"current-password"} minLength={setup?12:1} required /></div><Message text={message}/><button disabled={busy}>{busy?"Working…":setup?"Create admin account":"Sign in"}</button></form>{!setup&&<p className="small muted">First setup? <a href="/admin/setup">Create the first admin account</a></p>}</div></main>}

export function useAdminData<T>(url:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState("");useEffect(()=>{fetch(url).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load data.");setData(d)}).catch(e=>setError(e.message||"Network error."))},[url]);return {data,setData,error,setError}}
